language: c
compiler:
  - gcc
  - clang

before_install:

  ###
  # Install dependencies from a pre-built binary.
  ###
  - cd /
  - sudo wget http://www.unidata.ucar.edu/downloads/netcdf/ftp/travisdeps.tar.bz2
  - sudo tar -jxf travisdeps.tar.bz2
  - cd -

  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libcurl4-openssl-dev m4 wget autoconf libtool clang libjpeg8-dev
 
install:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j 4
  - make test
